# Generated by Django 6.0.5 on 2026-05-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password_last_changed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
