# Generated by Django 5.2.13 on 2026-05-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_notes_to_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='initiator_role',
            field=models.CharField(choices=[('doctor', 'doctor'), ('patient', 'patient')], default='patient', max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
